package com.galileo.netbeans.module;

import java.io.File;
import java.util.Collection;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.NbBundle;
import org.openide.util.NbCollections;

public final class PlaylistVisualPanel2 extends JPanel {

   public static final String PROP_TRACKS = "tracks";

   private DefaultListModel model = new DefaultListModel();

   public PlaylistVisualPanel2() {
      initComponents();
      tracks.setModel(model);
   }

   @Override
   public String getName() {
      return NbBundle.getBundle(PlaylistWizardPanel2.class).getString("Panel2.Name");
   }

   public Collection<File> getTracks() {
      return Collections.list(NbCollections.checkedEnumerationByFilter(model.elements(), File.class, false));
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTrack = new javax.swing.JButton();
        removeTrack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tracks = new javax.swing.JList();

        org.openide.awt.Mnemonics.setLocalizedText(addTrack, "Add...");
        addTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrackActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeTrack, "Delete");
        removeTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTrackActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tracks);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(removeTrack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addTrack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addTrack)
                    .add(removeTrack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void removeTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTrackActionPerformed
   int index = tracks.getSelectedIndex();
   if(index != -1) {
      model.remove(index);
   }
}//GEN-LAST:event_removeTrackActionPerformed

   private void addTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrackActionPerformed
   JFileChooser chooser = new JFileChooser();
   chooser.setFileFilter(new FileNameExtensionFilter("MP3 Music files", "mp3"));
   chooser.setMultiSelectionEnabled(true);

   if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      for(File f : chooser.getSelectedFiles()) {
         model.addElement(f);
      }
   }
}//GEN-LAST:event_addTrackActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeTrack;
    private javax.swing.JList tracks;
    // End of variables declaration//GEN-END:variables
  
}
